src/TicketManagement.Web/Models/Events/EventAreaViewModel.cs
using System.Collections.Generic;
using System.Linq;
using TicketManagement.BusinessLogic.ModelsDTO;

namespace TicketManagement.Web.Models.Events
{
    /// <summary>
    /// EventArea view model.
    /// </summary>
    public class EventAreaViewModel
    {
        /// <summary>
        /// Gets or sets EventArea.
        /// </summary>
        public EventAreaDto EventArea { get; set; }

        /// <summary>
        /// Gets max X coordinate from event seats in event area.
        /// If there are no event seats in event area, then will return 0.
        /// </summary>
        public int MaxXCoord
        {
            get
            {
                return EventSeats.Count > 0 ? EventSeats.Max(x => x.Row) : 0;
            }
        }

        /// <summary>
        /// Gets max Y coordinate.
        /// If there are no event seats in event area, then will return 0.
        /// </summary>
        public int MaxYCoord
        {
            get
            {
                return EventSeats.Count > 0 ? EventSeats.Max(x => x.Number) : 0;
            }
        }

        /// <summary>
        /// Gets or sets event seats in this event area.
        /// </summary>
        public List<EventSeatDto> EventSeats { get; set; }

        /// <summary>
        /// Checking that event seat with X and Y coordinate in event area exist.
        /// </summary>
        /// <param name="x">X coordinate.</param>
        /// <param name="y">Y coordinate.</param>
        /// <returns>True if exists and false if does not.</returns>
        public bool CheckSeatForExist(int x, int y)
        {
            var seat = EventSeats.FirstOrDefault(e => e.Row == x && e.Number == y);
            if (seat is not null)
            {
                return true;
            }

            return false;
        }
    }
}

src/TicketManagement.Web/Models/Events/EventAreaViewModelInEvent.cs
using System.Collections.Generic;
using System.Linq;
using TicketManagement.Web.ModelsDTO;

namespace TicketManagement.Web.Models.Events
{
    /// <summary>
    /// EventArea view model.
    /// </summary>
    public class EventAreaViewModelInEvent
    {
        /// <summary>
        /// Gets or sets EventArea.
        /// </summary>
        public EventAreaDto EventArea { get; set; }

        /// <summary>
        /// Gets max X coordinate from event seats in event area.
        /// If there are no event seats in event area, then will return 0.
        /// </summary>
        public int MaxXCoord
        {
            get
            {
                return EventSeats is null || EventSeats.Count <= 0 ? 0 : EventSeats.Max(x => x.Row);
            }
        }

        /// <summary>
        /// Gets max Y coordinate.
        /// If there are no event seats in event area, then will return 0.
        /// </summary>
        public int MaxYCoord
        {
            get
            {
                return EventSeats is null || EventSeats.Count <= 0 ? 0 : EventSeats.Max(x => x.Number);
            }
        }

        /// <summary>
        /// Gets or sets event seats in this event area.
        /// </summary>
        public List<EventSeatDto> EventSeats { get; set; }

        /// <summary>
        /// Checking that event seat with X and Y coordinate in event area exist.
        /// </summary>
        /// <param name="x">X coordinate.</param>
        /// <param name="y">Y coordinate.</param>
        /// <returns>True if exists and false if does not.</returns>
        public bool CheckSeatForExist(int x, int y)
        {
            var seat = EventSeats.FirstOrDefault(e => e.Row == x && e.Number == y);
            if (seat is not null)
            {
                return true;
            }

            return false;
        }
    }
}

src/TicketManagement.Web/Models/Events/EventViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using TicketManagement.Web.ModelsDTO;

namespace TicketManagement.Web.Models.Events
{
    /// <summary>
    /// Event view model.
    /// </summary>
    public class EventViewModel
    {
        /// <summary>
        /// Gets or sets id.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets name.
        /// </summary>
        [Required(ErrorMessage = "FieldRequired")]
        [Display(Name = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets description.
        /// </summary>
        [Required(ErrorMessage = "FieldRequired")]
        [Display(Name = "Description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets layout's id.
        /// </summary>
        [Required(ErrorMessage = "FieldRequired")]
        [Display(Name = "LayoutId")]
        [Range(1, int.MaxValue)]
        public int LayoutId { get; set; }

        /// <summary>
        /// Gets or sets time when event starts.
        /// </summary>
        [Required(ErrorMessage = "FieldRequired")]
        [Display(Name = "TimeStart")]
        public DateTime TimeStart { get; set; }

        /// <summary>
        /// Gets or sets time when event ends.
        /// </summary>
        [Required(ErrorMessage = "FieldRequired")]
        [Display(Name = "TimeEnd")]
        public DateTime TimeEnd { get; set; }

        /// <summary>
        /// Gets or sets image URL.
        /// </summary>
        [Url(ErrorMessage = "WrongUrl")]
        [Display(Name = "ImageUrl")]
        [Required(ErrorMessage = "FieldRequired")]
        public string ImageUrl { get; set; }

        /// <summary>
        /// Gets or sets state for saving third party event in database.
        /// </summary>
        public bool Checked { get; set; }

        /// <summary>
        /// Gets or sets list of EventAreaViewModel objects.
        /// EventAreaViewModel objects represents event areas.
        /// </summary>
        public IList<EventAreaViewModelInEvent> EventAreas { get; set; }

        /// <summary>
        /// Gets max X coordinate from event areas in event.
        /// If there are no event seats in event area, then will return 0.
        /// </summary>
        public int MaxXCoord
        {
            get
            {
                return EventAreas is null || EventAreas.Count <= 0 ? 0 : EventAreas.Max(x => x.EventArea.CoordX);
            }
        }

        /// <summary>
        /// Gets max Y coordinate from event areas in event.
        /// If there are no event seats in event area, then will return 0.
        /// </summary>
        public int MaxYCoord
        {
            get
            {
                return EventAreas is null || EventAreas.Count <= 0 ? 0 : EventAreas.Max(x => x.EventArea.CoordY);
            }
        }

        /// <summary>
        /// Sorting event areas by X and Y coordinates.
        /// </summary>
        /// <returns>Sorted event areas.</returns>
        public List<EventAreaViewModelInEvent> SortedEventAreas() => EventAreas.OrderBy(x => x.EventArea.CoordX).ThenBy(y => y.EventArea.CoordY).ToList();

        /// <summary>
        /// Check that event area with X and Y coordinate exist.
        /// </summary>
        /// <param name="x">X coordinate.</param>
        /// <param name="y">Y coordinate.</param>
        /// <returns>True if exists and false if does not.</returns>
        public bool CheckAreaForExist(int x, int y)
        {
            var area = EventAreas.FirstOrDefault(e => e.EventArea.CoordX == x && e.EventArea.CoordY == y);
            if (area is not null && area.EventSeats.Count > 0)
            {
                return true;
            }

            return false;
        }
    }
}

src/TicketManagement.Web/Controllers/EventsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TicketManagement.Web.Extensions;
using TicketManagement.Web.Infrastructure;
using TicketManagement.Web.Interfaces.HttpClients;
using TicketManagement.Web.Models;
using TicketManagement.Web.Models.Events;
using TicketManagement.Web.Models.Tickets;

namespace TicketManagement.Web.Controllers
{
    /// <summary>
    /// Controller for events.
    /// </summary>
    [ResponseCache(CacheProfileName = "Caching")]
    [ExceptionFilter]
    public class EventsController : Controller
    {
        /// <summary>
        /// IEventManagerClient object.
        /// </summary>
        private readonly IEventManagerClient _eventManagerClient;

        /// <summary>
        /// IPurchaseClient object.
        /// </summary>
        private readonly IPurchaseFlowClient _purchaseClient;

        /// <summary>
        /// Initializes a new instance of the <see cref="EventsController"/> class.
        /// </summary>
        /// <param name="eventManagerClient">IEventManagerClient object.</param>
        /// <param name="purchaseClient">IPurchaseClient object.</param>
        public EventsController(IEventManagerClient eventManagerClient, IPurchaseFlowClient purchaseClient)
        {
            _eventManagerClient = eventManagerClient;
            _purchaseClient = purchaseClient;
        }

        /// <summary>
        /// Get all events.
        /// </summary>
        /// <param name="pageNumber">Page number.</param>
        /// <returns>Task with IActionResult.</returns>
        [HttpGet]
        [RedirectFilter("")]
        public async Task<IActionResult> Index(int pageNumber = 1)
        {
            var events = await _eventManagerClient.GetEventViewModels(HttpContext.GetJwtToken(), pageNumber);
            var nextEvents = await _eventManagerClient.GetEventViewModels(HttpContext.GetJwtToken(), pageNumber + 1);
            PageViewModel.NextPage = nextEvents is not null && nextEvents.Any();
            PageViewModel.PageNumber = pageNumber;
            return View(events);
        }

        /// <summary>
        /// Details about event.
        /// </summary>
        /// <param name="id">Id of event.</param>
        /// <returns>Task with IActionResult.</returns>
        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            return id is null ? NotFound() : View(await _eventManagerClient.EventDetails(HttpContext.GetJwtToken(), (int)id));
        }

        /// <summary>
        /// Create event.
        /// </summary>
        /// <returns>IActionResult.</returns>
        [Authorize(Roles = "admin, event manager")]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Create event.
        /// </summary>
        /// <param name="eventVm">Adding event.</param>
        /// <returns>Task with IActionResult.</returns>
        [Authorize(Roles = "admin, event manager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EventViewModel eventVm)
        {
            if (!ModelState.IsValid)
            {
                return View(eventVm);
            }

            await _eventManagerClient.CreateEvent(HttpContext.GetJwtToken(), eventVm);
            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// Edit event.
        /// </summary>
        /// <param name="id">Id of editing event.</param>
        /// <returns>Task with IActionResult.</returns>
        [Authorize(Roles = "admin, event manager")]
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            return id is null ? NotFound() : View(await _eventManagerClient.GetEventViewModelForEdit(HttpContext.GetJwtToken(), (int)id));
        }

        /// <summary>
        /// Edit event.
        /// </summary>
        /// <param name="id">Id of editing event.</param>
        /// <param name="eventVm">Edited event.</param>
        /// <returns>Task with IActionResult.</returns>
        [Authorize(Roles = "admin, event manager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EventViewModel eventVm)
        {
            if (id != eventVm.Id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                return View(eventVm);
            }

            try
            {
                await _eventManagerClient.EditEvent(HttpContext.GetJwtToken(), id, eventVm);
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict();
            }

            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// Delete event.
        /// </summary>
        /// <param name="id">Id of deleting event.</param>
        /// <returns>Task with IActionResult.</returns>
        [Authorize(Roles = "admin, event manager")]
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            return id is null ? NotFound() : View(await _eventManagerClient.GetEventViewModelForDelete(HttpContext.GetJwtToken(), (int)id));
        }

        /// <summary>
        /// Delete confirmation.
        /// </summary>
        /// <param name="id">Id of deleting event.</param>
        /// <returns>Task with IActionResult.</returns>
        [Authorize(Roles = "admin, event manager")]
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _eventManagerClient.DeleteEvent(HttpContext.GetJwtToken(), id);
            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// Buy ticket.
        /// </summary>
        /// <param name="eventSeatId">Event seat id.</param>
        /// <param name="price">Price for place.</param>
        /// <returns>TicketViewModel.</returns>
        [HttpGet("events/buy")]
        public async Task<IActionResult> Buy(int eventSeatId, double price)
        {
            var model = await _purchaseClient.GetTicketViewModelForBuy(HttpContext.GetJwtToken(), eventSeatId, price);
            return View(model);
        }

        /// <summary>
        /// Buy ticket.
        /// </summary>
        /// <param name="ticketVm">Ticket view model.</param>
        /// <returns>IActionResult.</returns>
        [HttpPost("events/buy")]
        public async Task<IActionResult> Buy(TicketViewModel ticketVm)
        {
            await _purchaseClient.UpdateEventSeatStateAfterBuyingTicket(HttpContext.GetJwtToken(), ticketVm);
            return RedirectToAction(nameof(Index), typeof(EventsController).GetControllerName());
        }
    }
}

src/TicketManagement.Web/Controllers/ThirdPartyEventsController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TicketManagement.Web.Extensions;
using TicketManagement.Web.Infrastructure;
using TicketManagement.Web.Interfaces.HttpClients;
using TicketManagement.Web.Models.Events;
using TicketManagement.Web.Models.ThirdPartyEvents;

namespace TicketManagement.Web.Controllers
{
    /// <summary>
    /// Controller for third party events.
    /// </summary>
    [Authorize(Roles = "admin, event manager")]
    [ResponseCache(CacheProfileName = "Caching")]
    [ExceptionFilter]
    public class ThirdPartyEventsController : Controller
    {
        /// <summary>
        /// IEventManagerClient object.
        /// </summary>
        private readonly IEventManagerClient _eventManagerClient;

        /// <summary>
        /// Initializes a new instance of the <see cref="ThirdPartyEventsController"/> class.
        /// </summary>
        /// <param name="eventManagerClient">IEventManagerClient object.</param>
        public ThirdPartyEventsController(IEventManagerClient eventManagerClient)
        {
            _eventManagerClient = eventManagerClient;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ShowEvents(IFormFile file)
        {
            using var stream = file.OpenReadStream();
            byte[] fileData = new byte[stream.Length];
            await stream.ReadAsync(fileData);
            var data = new ThirdPartyEventData
            {
                BytesData = fileData,
            };
            return View(await _eventManagerClient.GetThirdPartyEventViewModels(HttpContext.GetJwtToken(), data));
        }

        [HttpPost]
        public async Task<IActionResult> SaveToDatabaseAsync(IEnumerable<EventViewModel> events)
        {
            await _eventManagerClient.SaveThirdPartyEventsToDatabase(HttpContext.GetJwtToken(), events);
            return RedirectToAction(nameof(Index), typeof(EventsController).GetControllerName());
        }
    }
}

src/TicketManagement.Web/Views/Events/Buy.cshtml
@model TicketViewModel
@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = @Localizer["Title"];
}

<h3>@Localizer["Sure"]@Model.Price$?</h3>
    <form asp-action="Buy">
        <input type="hidden" asp-for="@Model.EventSeatId" />
        <input type="hidden" asp-for="@Model.UserId" />
        <input type="hidden" asp-for="@Model.Price" />
        <input type="submit" value="@Localizer["Buy"]" class="btn btn-success" />
    </form>
<hr />
<div>
    <a class="btn btn-primary" asp-action="Index">@Localizer["Back"]</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/TicketManagement.Web/Views/Events/Create.cshtml
@model EventViewModel
@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = @Localizer["Title"];
}

<h1>@Localizer["Title"]</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LayoutId" class="control-label"></label>
                <input asp-for="LayoutId" class="form-control" />
                <span asp-validation-for="LayoutId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TimeStart" class="control-label"></label>
                <input asp-for="TimeStart" class="form-control" />
                <span asp-validation-for="TimeStart" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TimeEnd" class="control-label"></label>
                <input asp-for="TimeEnd" class="form-control" />
                <span asp-validation-for="TimeEnd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="@Localizer["Create"]" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>
<hr />
<div>
    <a class="btn btn-primary" asp-action="Index">@Localizer["Back"]</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/TicketManagement.Web/Views/Events/Delete.cshtml
@model EventViewModel
@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = @Localizer["Title"];
}

<h1>@Localizer["Title"]</h1>

<h3>@Localizer["Sure"]</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LayoutId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LayoutId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimeStart)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimeStart)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimeEnd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimeEnd)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="@Localizer["Delete"]" class="btn btn-danger" />
    </form>
    <hr />
    <a class="btn btn-primary" asp-action="Index">@Localizer["Back"]</a>
</div>

src/TicketManagement.Web/Views/Events/Details.cshtml
@model EventViewModel
@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = @Model.Name;
}

<h1 class="d-flex justify-content-center">@Model.Name</h1>

<div>
    <hr />
    <img class="img-fluid" src="@Model.ImageUrl" alt="@Localizer["Picture"]">
    <br />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LayoutId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LayoutId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimeStart)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimeStart)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimeEnd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimeEnd)
        </dd>
    </dl>
</div>
<hr />
@if (User.IsInRole("admin") || User.IsInRole("user") || User.IsInRole("event manager") || User.IsInRole("venue manager"))
{
    @if (Model.MaxXCoord != 0)
    {
        <h2 class="justify-content-center">@Localizer["Map"]</h2>
        <div>
        @{int areasNumber = 0;}
        @for (int i = 1; i <= Model.MaxXCoord; i++)
        {
            <div class="row">
            @for (int j = 1; j <= Model.MaxYCoord; j++)
            {
                if (Model.CheckAreaForExist(i, j))
                {
                    int seatsNumber = 0;
                    <div class="border col-3">
                    @{
                        var eventArea = Model.SortedEventAreas().ElementAt(areasNumber);
                        areasNumber++;
                    }
                    @for (int k = 1; k <= eventArea.MaxXCoord; k++)
                    {
                        <div class="row">
                            @for (int z = 1; z <= eventArea.MaxYCoord; z++)
                            {
                                if (eventArea.CheckSeatForExist(k, z))
                                {
                                    if (eventArea.EventSeats.ElementAt(seatsNumber).State == PlaceStatus.Occupied)
                                    {
                                        <a class="btn btn-danger">@k-@z</a>
                                    }
                                    else
                                    {
                                        <a asp-action="Buy" asp-route-eventSeatId="@eventArea.EventSeats.ElementAt(seatsNumber).Id" asp-route-price="@eventArea.EventArea.Price" class="btn btn-success">@k-@z</a>
                                    }
                                    seatsNumber++;
                                }
                            }
                        </div>
                    }
                    </div>
                }
            }
            </div>
        }
        </div>
        <hr />
    }
    else
    {
        <h2>@Localizer["NoPlaces"]</h2>
    }
}
else
{
    <h2>Register first to buy ticket!</h2>
}

@if (User.IsInRole("admin") || User.IsInRole("event manager"))
{
    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model.Id">@Localizer["Edit"]</a>
}
<a class="btn btn-primary" asp-action="Index">@Localizer["Back"]</a>

src/TicketManagement.Web/Views/Events/Edit.cshtml
@model EventViewModel
@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = @Localizer["Title"];
}

<h1>@Localizer["Title"]</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LayoutId" class="control-label"></label>
                <input asp-for="LayoutId" class="form-control" />
                <span asp-validation-for="LayoutId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TimeStart" class="control-label"></label>
                <input asp-for="TimeStart" class="form-control" />
                <span asp-validation-for="TimeStart" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TimeEnd" class="control-label"></label>
                <input asp-for="TimeEnd" class="form-control" />
                <span asp-validation-for="TimeEnd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="@Localizer["Save"]" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>
<hr />
<div>
    <a class="btn btn-primary" asp-action="Index">@Localizer["Back"]</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/TicketManagement.Web/Views/Events/Index.cshtml
@model IEnumerable<EventViewModel>
@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = @Localizer["Title"];
}

<h1 class="d-flex justify-content-center">@Localizer["Title"]</h1>
@if (User.IsInRole("admin") || User.IsInRole("event manager"))
{
    <p class="d-flex justify-content-center">
        <a class="btn btn-success" asp-action="Create">@Localizer["AddNew"]</a>
    </p>
    <p class="d-flex justify-content-center">
        <a class="btn btn-success" asp-controller="ThirdPartyEvents" asp-action="Index">@Localizer["AddThirdPartyEvents"]</a>
    </p>
}
<hr />
<div class="container">
    @for (int i = 0; i < Model.Count(); i += 3)
    {
        <div class="row">
            @for (int j = 0; j < 3 && i + j < Model.Count(); j++)
            {
                <div class="col">
                    <a asp-action="Details" asp-route-id="@Model.ElementAt(i + j).Id" class="d-flex justify-content-center text-reset text-decoration-none">
                        <figure>
                            <img src="@Model.ElementAt(i + j).ImageUrl" height="300" width="300" alt="@Localizer["Picture"]">
                            <figcaption class="d-flex justify-content-center">
                                <div>
                                    <h3 class="text-center">@Html.DisplayFor(modelItem => Model.ElementAt(i + j).Name)</h3>
                                    @if (User.IsInRole("admin") || User.IsInRole("event manager"))
                                    {
                                        <div class="row">
                                            <div class="col"><a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model.ElementAt(i + j).Id">@Localizer["Edit"]</a></div>
                                            <div class="col"><a class="btn btn-danger" asp-action="Delete" asp-route-id="@Model.ElementAt(i + j).Id">@Localizer["Delete"]</a></div>
                                        </div>
                                    }
                                </div>
                            </figcaption>
                        </figure>
                    </a>
                </div>
            }
        </div>
    }
</div>
@{
    int previousPage;
    int nextPage;
}
@if (PageViewModel.PageNumber > 1)
{
    <a class="btn btn-primary" asp-action="Index" asp-route-pageNumber="1">1</a>
    {
        previousPage = PageViewModel.PageNumber - 1;
    }
    <a class="btn btn-primary" asp-action="Index" asp-route-pageNumber="@previousPage">
        &lt;
    </a>
}
@if (PageViewModel.NextPage)
{
    {
        nextPage = PageViewModel.PageNumber + 1;
    }
    <a class="btn btn-primary" asp-action="Index" asp-route-pageNumber="@nextPage">
        >
    </a>
}